version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: skillbridge_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: skillbridge_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/db_init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: skillbridge_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth-service:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    container_name: skillbridge_auth_service
    ports:
      - "8082:8082"
    environment:
      - AUTH_SERVICE_PORT=8082
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillbridge_auth
      - DB_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - JWT_SECRET=your_jwt_secret_key_change_this_in_production
      - USER_SERVICE_URL=http://user-service:8081
    depends_on:
      - postgres
      - redis
      - user-service
    restart: on-failure

  user-service:
    build:
      context: .
      dockerfile: services/user/Dockerfile
    container_name: skillbridge_user_service
    ports:
      - "8081:8081"
    environment:
      - USER_SERVICE_PORT=8081
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillbridge_auth
      - DB_SSL_MODE=disable
    depends_on:
      - postgres
    restart: on-failure

  api-gateway:
    image: nginx:alpine
    container_name: skillbridge_api_gateway
    ports:
      - "8080:8080"
    volumes:
      - ./services/api-gateway/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth-service
      - user-service
    restart: on-failure

volumes:
  postgres_data:
  redis_data:
