version: '3.8'

services:
  # User Service
  user-service:
    build:
      context: ..
      dockerfile: backend/services/user/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillbridge_user
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - JWT_ACCESS_EXPIRY=24h
      - JWT_REFRESH_EXPIRY=168h
      - JWT_VERIFICATION_EXPIRY=48h
      - JWT_PASSWORD_RESET_EXPIRY=24h
    depends_on:
      - postgres
    networks:
      - skillbridge-network
    restart: on-failure

  # Authentication Service
  auth-service:
    build:
      context: ..
      dockerfile: backend/services/auth/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillbridge_auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - JWT_ACCESS_EXPIRY=24h
      - JWT_REFRESH_EXPIRY=168h
      - JWT_VERIFICATION_EXPIRY=48h
      - JWT_PASSWORD_RESET_EXPIRY=24h
    depends_on:
      - postgres
      - redis
    networks:
      - skillbridge-network
    restart: on-failure

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    networks:
      - skillbridge-network

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - skillbridge-network

networks:
  skillbridge-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data: