version: '3.8'

services:
  # API Gateway
  api-gateway:
    build:
      context: ./
      dockerfile: services/api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_URL=http://user-service:8081
      - AUTH_SERVICE_URL=http://auth-service:8082
    depends_on:
      - user-service
      - auth-service
    networks:
      - skillbridge-network

  # User Service
  user-service:
    build:
      context: ./
      dockerfile: services/user/Dockerfile
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillbridge_user
    depends_on:
      - postgres
    networks:
      - skillbridge-network

  # Authentication Service
  auth-service:
    build:
      context: ./
      dockerfile: services/auth/Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=skillbridge_auth
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - JWT_EXPIRY=24h
    depends_on:
      - postgres
      - redis
    networks:
      - skillbridge-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=skillbridge_user,skillbridge_auth
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/create-multiple-postgresql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-postgresql-databases.sh
    networks:
      - skillbridge-network

  # Redis
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - skillbridge-network

networks:
  skillbridge-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
